name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          PUBLIC_URL: /covid19-world-monitor
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REACT_APP_MapboxAccessToken: ${{ secrets.REACT_APP_MapboxAccessToken }}
          REACT_APP_CovidAPI_Key: ${{ secrets.REACT_APP_CovidAPI_Key }}
          REACT_APP_CovidApi_Host: ${{ secrets.REACT_APP_CovidApi_Host }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: yarn && yarn build
